db_type:
  pgsql: true
  sqlite: true
  mysql: true
db:
  # lulumu:
  #   dsn: "host=127.0.0.1 user=postgres password=a123456 dbname=lulumu port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  #   type: "pgsql"
  lulumu:
    dsn: "host=127.0.0.1 user=postgres password=UU,kYoL:N_8gdIeRGpub dbname=lulumu port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    type: "pgsql"
defalut: lulumu